server:
  port: 8002
mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.wangling.springcloud.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: mircoservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: wl9010
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/://eureka7003.com/eureka/
info:
  app.name: wangling-microservicecloud
  company.name: wangling
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}